### ISSUE TITLE
ni ga issue

### ISSUE THREAD

**Issue by Danielle-360** [BenjaminJones-UOP/Wowwbot#11]
review sensitivity for bannable terms being picked up in other words eg mini game

**Comment by BenjaminJones-UOP** [comment]
if (e.ChatMessage.Message.Contains(timedoutWord, **StringComparison.OrdinalIgnoreCase**))

add bold into the argument and test

**Comment by Danielle-360** [comment]
/// </summary>
        /// <param name="toCheck">Sentence to check.</param>
        /// <param name="profanity">Profanity to look for.</param>
        /// <returns>Tuple of the following format (start character, end character, found enclosed word).
        /// If no enclosed word is found then return null.</returns>
        public (int, int, string)? GetCompleteWord(string toCheck, string profanity)
        {
            if (string.IsNullOrEmpty(toCheck))
            {
                return null;
            }

            string profanityLowerCase = profanity.ToLower(CultureInfo.InvariantCulture);
            string toCheckLowerCase = toCheck.ToLower(CultureInfo.InvariantCulture);

            if (toCheckLowerCase.Contains(profanityLowerCase))
            {
                var startIndex = toCheckLowerCase.IndexOf(profanityLowerCase, StringComparison.Ordinal);
                var endIndex = startIndex;

                // Work backwards in string to get to the start of the word.
                while (startIndex > 0)
                {
                    if (toCheck[startIndex - 1] == ' ' || char.IsPunctuation(toCheck[startIndex - 1]))
                    {
                        break;
                    }

                    startIndex -= 1;
                }

                // Work forwards to get to the end of the word.
                while (endIndex < toCheck.Length)
                {
                    if (toCheck[endIndex] == ' ' || char.IsPunctuation(toCheck[endIndex]))
                    {
                        break;
                    }

                    endIndex += 1;
                }

                return (startIndex, endIndex, toCheckLowerCase.Substring(startIndex, endIndex - startIndex).ToLower(CultureInfo.InvariantCulture));
            }

            return null;
        }

**Comment by BenjaminJones-UOP** [comment]
> if (e.ChatMessage.Message.Contains(timedoutWord, **StringComparison.OrdinalIgnoreCase**))
> 
> add bold into the argument and test

Changed to splitting the message up and using **Equals** instead of **Contains** 

This seems to have solved the issue of spaces being ignored and minigame can be typed without triggering niga
